function stats_table = addOneSampleTtestStatsTableRow(stats_table, ...
    group1, p_value_threshold, options)

arguments
    stats_table (:, :) table
    group1 (:, 1) double
    p_value_threshold (1, 1) double
    options.dependent_variable (1, 1) string = ""
    options.subset_factors (1, :) string = ""
    options.subset_levels (1, :) string = ""

end

% Paired t-test
[~, p, ci, stats] = ttest(group1);

% Cohen's d
d = mean(group1) / std(group1);

% Save in the table
stats_table = addStatsTableRow(stats_table, group1, NaN, ...
        test_name="one_sample_ttest", ...
        tail="two_sided", ...
        dependent_variable=options.dependent_variable, ...
        subset_factors=options.subset_factors, ...
        subset_levels=options.subset_levels, ...
        degrees_freedom=stats.df, ...
        t_stats=stats.tstat, ...
        p_value=p, ...
        cohens_d=d, ...
        p_value_threshold=p_value_threshold, ...
        conf_interval_95=ci);

end
