function stats_table = addPearsonCorrelationTtestStatsTableRow(stats_table, ...
    group1, group2, p_value_threshold, options)

arguments
    stats_table (:, :) table
    group1 (:, 1) double
    group2 (:, 1) double
    p_value_threshold (1, 1) double
    options.dependent_variable (1, 1) string = ""
    options.independent_variable (1, 1) string = ""
    options.independent_variable_levels (1, :) string = ""
    options.subset_factors (1, :) string = ""
    options.subset_levels (1, :) string = ""

end

% Pearson correlation
[rho, p] = corr(group1, group2, Type="Pearson");

% Save in the table
stats_table = addStatsTableRow(stats_table, group1, group2, ...
        test_name="pearson_corr", ...
        tail="", ...
        dependent_variable=options.dependent_variable, ...
        independent_variable=options.independent_variable, ...
        independent_variable_levels=options.independent_variable_levels, ...
        subset_factors=options.subset_factors, ...
        subset_levels=options.subset_levels, ...
        degrees_freedom=length(group1) - 2, ...
        r=rho, ...
        p_value=p, ...
        p_value_threshold=p_value_threshold);

end
