function stats_table = addPairedTtestStatsTableRow(stats_table, ...
    group1, group2, p_value_threshold, options)

arguments
    stats_table (:, :) table
    group1 (:, 1) double
    group2 (:, 1) double
    p_value_threshold (1, 1) double
    options.dependent_variable (1, 1) string = ""
    options.independent_variable (1, 1) string = ""
    options.independent_variable_levels (1, :) string = ""
    options.subset_factors (1, :) string = ""
    options.subset_levels (1, :) string = ""

end

% Paired t-test
[~, p, ci, stats] = ttest(group1, group2);

% Cohen's d
group_diff = group1 - group2;
d = mean(group_diff) / std(group_diff);

% Save in the table
stats_table = addStatsTableRow(stats_table, group1, group2, ...
        test_name="paired_ttest", ...
        tail="two_sided", ...
        dependent_variable=options.dependent_variable, ...
        independent_variable=options.independent_variable, ...
        independent_variable_levels=options.independent_variable_levels, ...
        subset_factors=options.subset_factors, ...
        subset_levels=options.subset_levels, ...
        degrees_freedom=stats.df, ...
        t_stats=stats.tstat, ...
        p_value=p, ...
        cohens_d=d, ...
        p_value_threshold=p_value_threshold, ...
        conf_interval_95=ci);

end
