function stats_table = addStatsTableRow(stats_table, group1, group2, options)

arguments
    stats_table (:, :) table
    group1 (:, 1) double
    group2 (:, 1) double
    options.test_name (1, 1) string = ""
    options.tail (1, 1) string = ""
    options.dependent_variable (1, 1) string = ""
    options.independent_variable (1, 1) string = ""
    options.independent_variable_levels (1, :) string = ""
    options.subset_factors (1, :) string = ""
    options.subset_levels (1, :) string = ""
    options.degrees_freedom (1, 1) double
    options.t_stats (1, :) double = NaN
    options.r (1, 1) double = NaN
    options.beta (1, :) double = NaN
    options.p_value (1, :) double = NaN
    options.p_value_threshold (1, :) double = NaN
    options.conf_interval_95 (1, 2) double = NaN

end

stats_table = [stats_table ; ...
        {options.test_name, options.tail, ...
        options.dependent_variable, ...
        options.independent_variable, {options.independent_variable_levels}, ...
        {options.subset_factors}, {options.subset_levels}, ...
        [length(group1), length(group2)], ...
        options.degrees_freedom, ...
        [mean(group1), mean(group2)], ...
        [std(group1) / sqrt(length(group1)), std(group2) / sqrt(length(group2))], ...
        {group1, group2}, ...
        options.t_stats, ...
        options.r, ...
        options.beta, ...
        options.p_value, ...
        options.p_value_threshold, ...
        options.conf_interval_95}];

end