function stats_table = initializeStatsTable()

% Define table column names
variable_names = [...
    ... Define which test is performed
    "test_name", "tail", ...
    "dependent_variable", ...
    "independent_variable", "independent_variable_levels", ...
    "subset_factors", "subset_levels", ...
    ... Describe the data within each group
    "sample_size", ...
    "degrees_freedom", ...
    "mean", ...
    "standard_error", ...
    "raw_data", ...
    ... Describe the test results
    "t_stats", ...
    "r", ...
    "beta", ...
    "p_value", ...
    "p_value_threshold"...
    "conf_interval_95", ...
    ];

% Define table column types
variable_types = [...
    "string", "string", ...
    "string", ...
    "string", "cell", ...
    "cell", "cell", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    ];

% Create the table
stats_table = table(...
    Size=[0, length(variable_names)], ...
    VariableNames=variable_names, ...
    VariableTypes=variable_types);

end
