% Fig. S3 | CCM matrices for neural populations recorded in either the OFC,
% dlPFC or ACC. Panels on the left show CCM matrices (color code depicts 
% he Pearson correlation coefficients between vectors of t-statistics
% associated with regression coefficient estimates for the kth attended
% cue at cue onset time t, across integration units, going from blue -low
% correlation- to red -high correlation-), organized by cue index in the
% sequence (k=1, 2 or 3) and response time (t=1, 2 or 3). Panels on the
% right show CCM cells from monkey M (y-axis) plotted against RDM cells
% from monkey F (x-axis). Asterisks indicate significant correlations, with
% p-value < 0.0007 (correction for multiple comparisons across CCM cells).


%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

NeuralGeometry = load(fullfile(getPath("MonkeyData"), "NeuralGeometry.mat"));


%% === Generate figure ====================================================

% Initialize the figure
f = figure(...
    Name = "Figure S3: CCM matrices for neural populations recorded in either the OFC, dlPFC or ACC.", ...
    Units = "centimeters", ...
    Position = [0, 0, 18, 14], ...
    NumberTitle="off", ...
    Color = "w");
movegui(f, "center");

% Define the layout
t = tiledlayout(f, 3, 4, ...
    TileSpacing="tight", ...
    Units="centimeters", ...
    Position=[2, 0.5, 16, 12.5]);

% Subplots
plotCCM(nexttile(1, [1, 1]), ...
    NeuralGeometry.OFC.Franck.CCM_option, ...
    NeuralGeometry.OFC.Franck.CCM_attribute, ...
    NeuralGeometry.OFC.Franck.CCM_option_p, ...
    NeuralGeometry.OFC.Franck.CCM_attribute_p, ...
    y_label="OFC", ...
    title="Monkey F", ...
    labels=[true, true, false, false]);
plotCCM(nexttile(2, [1, 1]), ...
    NeuralGeometry.OFC.Miles.CCM_option, ...
    NeuralGeometry.OFC.Miles.CCM_attribute, ...
    NeuralGeometry.OFC.Miles.CCM_option_p, ...
    NeuralGeometry.OFC.Miles.CCM_attribute_p, ...
    title="Monkey M", ...
    labels=[true, false, false, false]);
plotCCM(nexttile(3, [1, 1]), ...
    NeuralGeometry.OFC.both.CCM_option, ...
    NeuralGeometry.OFC.both.CCM_attribute, ...
    NeuralGeometry.OFC.both.CCM_option_p, ...
    NeuralGeometry.OFC.both.CCM_attribute_p, ...
    title="Both monkeys", ...
    labels=[true, false, false, false]);
select_half_CCM = triu(true(size(NeuralGeometry.OFC.Franck.CCM_option)), 1);
plotNeuralGeometryComparison(nexttile(4, [1, 1]), ...
    [NeuralGeometry.OFC.Franck.CCM_option(select_half_CCM) ; NeuralGeometry.OFC.Franck.CCM_attribute(select_half_CCM)], ...
    [NeuralGeometry.OFC.Miles.CCM_option(select_half_CCM) ; NeuralGeometry.OFC.Miles.CCM_attribute(select_half_CCM)]);
plotCCM(nexttile(5, [1, 1]), ...
    NeuralGeometry.dlPFC.Franck.CCM_option, ...
    NeuralGeometry.dlPFC.Franck.CCM_attribute, ...
    NeuralGeometry.dlPFC.Franck.CCM_option_p, ...
    NeuralGeometry.dlPFC.Franck.CCM_attribute_p, ...
    y_label="dlPFC", ...
    labels=[false, true, false, false]);
plotCCM(nexttile(6, [1, 1]), ...
    NeuralGeometry.dlPFC.Miles.CCM_option, ...
    NeuralGeometry.dlPFC.Miles.CCM_attribute, ...
    NeuralGeometry.dlPFC.Miles.CCM_option_p, ...
    NeuralGeometry.dlPFC.Miles.CCM_attribute_p, ...
    labels=[false, false, false, false]);
plotCCM(nexttile(7, [1, 1]), ...
    NeuralGeometry.dlPFC.both.CCM_option, ...
    NeuralGeometry.dlPFC.both.CCM_attribute, ...
    NeuralGeometry.dlPFC.both.CCM_option_p, ...
    NeuralGeometry.dlPFC.both.CCM_attribute_p, ...
    labels=[false, false, false, false]);
plotNeuralGeometryComparison(nexttile(8, [1, 1]), ...
    [NeuralGeometry.dlPFC.Franck.CCM_option(select_half_CCM) ; NeuralGeometry.dlPFC.Franck.CCM_attribute(select_half_CCM)], ...
    [NeuralGeometry.dlPFC.Miles.CCM_option(select_half_CCM) ; NeuralGeometry.dlPFC.Miles.CCM_attribute(select_half_CCM)]);
plotCCM(nexttile(9, [1, 1]), ...
    NeuralGeometry.ACC.Franck.CCM_option, ...
    NeuralGeometry.ACC.Franck.CCM_attribute, ...
    NeuralGeometry.ACC.Franck.CCM_option_p, ...
    NeuralGeometry.ACC.Franck.CCM_attribute_p, ...
    y_label="ACC", ...
    labels=[false, true, false, false]);
plotCCM(nexttile(10, [1, 1]), ...
    NeuralGeometry.ACC.Miles.CCM_option, ...
    NeuralGeometry.ACC.Miles.CCM_attribute, ...
    NeuralGeometry.ACC.Miles.CCM_option_p, ...
    NeuralGeometry.ACC.Miles.CCM_attribute_p, ...
    labels=[false, false, false, false]);
plotCCM(nexttile(11, [1, 1]), ...
    NeuralGeometry.ACC.both.CCM_option, ...
    NeuralGeometry.ACC.both.CCM_attribute, ...
    NeuralGeometry.ACC.both.CCM_option_p, ...
    NeuralGeometry.ACC.both.CCM_attribute_p, ...
    labels=[false, false, false, false]);
plotNeuralGeometryComparison(nexttile(12, [1, 1]), ...
    [NeuralGeometry.ACC.Franck.CCM_option(select_half_CCM) ; NeuralGeometry.ACC.Franck.CCM_attribute(select_half_CCM)], ...
    [NeuralGeometry.ACC.Miles.CCM_option(select_half_CCM) ; NeuralGeometry.ACC.Miles.CCM_attribute(select_half_CCM)]);

% Colorbar
ax_top = nexttile(1, [1, 1]);
ax_bottom = nexttile(9, [1, 1]);
ax_top.Units = "centimeters";
ax_bottom.Units = "centimeters";
cb_pos = [...
    ax_top.Position(1) - 2.1, ...
    ax_bottom.Position(2) - 1.2, ...
    0.4, ...
    ax_top.Position(2) + ax_top.Position(4) - ax_bottom.Position(2)];
cb = colorbar(ax_top, ...
    Ticks=[-1, 0, 1], Location="westoutside");
cb.Label.String = "Correlation";
cb.Label.FontSize = 8;
cb.Units = "centimeters";
cb.Label.Position(1) = cb.Label.Position(1) + 0.45;
cb.Position = cb_pos;

% Set font globally
fontname(f, "arial");


%% === Save figure ========================================================

exportgraphics(f, fullfile(getPath("Figures"), "figS3.pdf"), ContentType="vector");
exportgraphics(f, fullfile(getPath("Figures"), "figS3.png"), Resolution=600);
