% Fig. S2 | RDM matrices at first cue onset for neural populations recorded
% in either the OFC, dlPFC or ACC. Panels on the left show RDM matrices
% (color code depicts the Pearson correlation coefficients between activity
% patterns that are elicited in response to first cue, going from blue -low
% correlation- to red -high correlation-), organized by cue spatial side
% (left:L or right:R), type (probability or magnitude) and rank (from 1 to
% 5). Panels on the right show RDM cells from monkey M (y-axis) plotted
% against RDM cells from monkey F (x-axis). 


%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

NeuralGeometry = load(fullfile(getPath("MonkeyData"), "NeuralGeometry.mat"));


%% === Generate figure ====================================================

% Initialize the figure
f = figure(...
    Name = "Figure S2: RDM matrices at first cue onset for neural populations recorded in either the OFC, dlPFC or ACC.", ...
    Units = "centimeters", ...
    Position = [0, 0, 18, 14], ...
    NumberTitle="off", ...
    Color = "w");
movegui(f, "center");

% Define the layout
t = tiledlayout(f, 3, 4, ...
    TileSpacing="tight", ...
    Units="centimeters", ...
    Position=[1.7, 0.5, 16.3, 12.5]);

% Subplots
plotRDM(nexttile(1, [1, 1]), NeuralGeometry.OFC.Franck.RDM, ...
    colorbar_lim=0.3, ...
    y_label="OFC", ...
    title="Monkey F", ...
    labels=[true, true, false, false]);
plotRDM(nexttile(2, [1, 1]), NeuralGeometry.OFC.Miles.RDM, ...
    colorbar_lim=0.3, ...
    title="Monkey M", ...
    labels=[true, true, false, false]);
plotRDM(nexttile(3, [1, 1]), NeuralGeometry.OFC.both.RDM, ...
    colorbar_lim=0.3, ...
    title="Both monkeys", ...
    labels=[true, true, false, false]);
select_half_RDM = triu(true(size(NeuralGeometry.OFC.Franck.RDM)), 1);
plotNeuralGeometryComparison(nexttile(4, [1, 1]), ...
    NeuralGeometry.OFC.Franck.RDM(select_half_RDM), ...
    NeuralGeometry.OFC.Miles.RDM(select_half_RDM));
plotRDM(nexttile(5, [1, 1]), NeuralGeometry.dlPFC.Franck.RDM, ...
    colorbar_lim=0.3, ...
    y_label="dlPFC", ...
    labels=[true, true, false, false]);
plotRDM(nexttile(6, [1, 1]), NeuralGeometry.dlPFC.Miles.RDM, ...
    colorbar_lim=0.3, ...
    labels=[true, true, false, false]);
plotRDM(nexttile(7, [1, 1]), NeuralGeometry.dlPFC.both.RDM, ...
    colorbar_lim=0.3, ...
    labels=[true, true, false, false]);
plotNeuralGeometryComparison(nexttile(8, [1, 1]), ...
    NeuralGeometry.dlPFC.Franck.RDM(select_half_RDM), ...
    NeuralGeometry.dlPFC.Miles.RDM(select_half_RDM));
plotRDM(nexttile(9, [1, 1]), NeuralGeometry.ACC.Franck.RDM, ...
    colorbar_lim=0.3, ...
    y_label="ACC", ...
    labels=[true, true, false, false]);
plotRDM(nexttile(10, [1, 1]), NeuralGeometry.ACC.Miles.RDM, ...
    colorbar_lim=0.3, ...
    labels=[true, true, false, false]);
plotRDM(nexttile(11, [1, 1]), NeuralGeometry.ACC.both.RDM, ...
    colorbar_lim=0.3, ...
    labels=[true, true, false, false]);
plotNeuralGeometryComparison(nexttile(12, [1, 1]), ...
    NeuralGeometry.ACC.Franck.RDM(select_half_RDM), ...
    NeuralGeometry.ACC.Miles.RDM(select_half_RDM));

% Colorbar
ax_top = nexttile(1, [1, 1]);
ax_bottom = nexttile(9, [1, 1]);
ax_top.Units = "centimeters";
ax_bottom.Units = "centimeters";
cb_pos = [...
    ax_top.Position(1) - 2.23, ...
    ax_bottom.Position(2) - 1.2, ...
    0.4, ...
    ax_top.Position(2) + ax_top.Position(4) - ax_bottom.Position(2)];
cb = colorbar(ax_top, ...
    Ticks=[-0.3, 0, 0.3], Location="westoutside");
cb.Label.String = "Correlation";
cb.Label.FontSize = 8;
cb.Units = "centimeters";
cb.Label.Position(1) = cb.Label.Position(1) + 0.9;
cb.Position = cb_pos;

% Set font globally
fontname(f, "arial");


%% === Save figure ========================================================

exportgraphics(f, fullfile(getPath("Figures"), "figS2.pdf"), ContentType="vector");
exportgraphics(f, fullfile(getPath("Figures"), "figS2.png"), Resolution=600);
