% Fig. S7 | Evaluating the accuracy of neural predictions of irrational
% RNNs directly trained on monkeys’ choices.
% 
%   - a, Neural distance trajectories between OFC and RNN cohorts during
% direct irrational training. Points show the average distance between
% activity patterns of OFC recordings and RNN models (across the 1,000 RNN
% instances), computed using either RDMs (x-axis) or CCMs (y-axis) metrics,
% either at initialization (black dots) or at training convergence (see
% legend).
% 
%   - b and c, Same, for DLPFC and ACC neurons, respectively.
% 
%   - d, Distributions (across cohort instances) of final neural CCM
% distances between irrational models and the OFC, the DLPFC and the ACC,
% for value synthesis (blue) and value comparison (orange) RNNs that rely
% on a temporal option identity format and an attentional value readout
% format. Asterisks indicate significant differences between distances with
% OFC on the one hand, and both DLPFC and ACC on the other hand, with
% p-value < 0.005. This panel reproduces Fig 3g in the main text.


%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

DataFranck = loadMeasureResults([...
        "config_ID", "is_irrational", "fit_step", ...
        "dist_RDM_avg_OFC", "dist_CCM_avg_OFC", ...
        "dist_RDM_avg_dlPFC", "dist_CCM_avg_dlPFC", ...
        "dist_RDM_avg_ACC", "dist_CCM_avg_ACC"], ...
        "irrational_Franck_last");

DataMiles = loadMeasureResults([...
        "config_ID", "is_irrational", "fit_step", ...
        "dist_RDM_avg_OFC", "dist_CCM_avg_OFC", ...
        "dist_RDM_avg_dlPFC", "dist_CCM_avg_dlPFC", ...
        "dist_RDM_avg_ACC", "dist_CCM_avg_ACC"], ...
        "irrational_Miles_last");

% Merge data across both monkeys
Data = struct();
for field = string(fieldnames(DataFranck))'
    Data.(field) = [DataFranck.(field), DataMiles.(field)];
end


%% === Generate figure ====================================================

% Initialize the figure
f = figure(...
    Name = "Figure S7: evaluating the accuracy of neural predictions of irrational RNNs directly trained on monkeys' choices", ...
    Units = "centimeters", ...
    Position = [0, 0, 18, 9.5], ...
    NumberTitle="off", ...
    Color = "w");
movegui(f, "center");

% Define the layout
t = tiledlayout(f, 2, 3, ...
    TileSpacing="loose", ...
    Units="centimeters", ...
    Position=[1.3, 0.8, 16.4, 8.3]);

% Subplots
plotSimpleNeuralDistanceTrajectory(nexttile(1, [1, 1]), Data, ...
    area="OFC", ...
    fit_label="irrational", ...
    x_lim=[0.3, 0.7], ...
    y_lim=[2, 4], ...
    title="Distance with the OFC");
plotSimpleNeuralDistanceTrajectory(nexttile(2, [1, 1]), Data, ...
    area="dlPFC", ...
    fit_label="irrational", ...
    x_lim=[0.3, 0.7], ...
    y_lim=[2, 4], ...
    title="Distance with the dlPFC");
plotSimpleNeuralDistanceTrajectory(nexttile(3, [1, 1]), Data, ...
    area="ACC", ...
    fit_label="irrational", ...
    x_lim=[0.3, 0.7], ...
    y_lim=[2, 4], ...
    title="Distance with the ACC");
plotCCMdistanceDistribPerArea(nexttile(6, [1, 1]), Data);

% Legend
ghost_plots = gobjects(1, 15);
ax = nexttile(3, [1, 1]);
hold(ax, "on");
ghost_plots(1) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfnetwork value");
ghost_plots(2) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfcomputation");
ghost_plots(3) = plot(ax, NaN, NaN, Marker="s", MarkerFaceColor=defineModelColor(1), MarkerEdgeColor="none", LineStyle="none", ...
    DisplayName="comparison");
ghost_plots(4) = plot(ax, NaN, NaN, Marker="s", MarkerFaceColor=defineModelColor(2), MarkerEdgeColor="none", LineStyle="none", ...
    DisplayName="synthesis");
ghost_plots(5) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="");
ghost_plots(6) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfattended option");
ghost_plots(7) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfidentity format");
ghost_plots(8) = plot(ax, NaN, NaN, Color="k", LineStyle=defineModelLineStyle(1), LineWidth=0.7, ...
    DisplayName=" spatial");
ghost_plots(9) = plot(ax, NaN, NaN, Color="k", LineStyle=defineModelLineStyle(7), LineWidth=0.7, ...
    DisplayName=" temporal");
ghost_plots(10) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="");
ghost_plots(11) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfvalue readout");
ghost_plots(12) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfformat");
ghost_plots(13) = plot(ax, NaN, NaN, Marker=defineModelMarker(1), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="spatial");
ghost_plots(14) = plot(ax, NaN, NaN, Marker=defineModelMarker(3), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="temporal");
ghost_plots(15) = plot(ax, NaN, NaN, Marker=defineModelMarker(5), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="attentional");
hold(ax, "off");
ax_left = nexttile(1, [1, 1]);
ax_left.Units = "centimeters";
ax_center = nexttile(2, [1, 1]);
ax_center.Units = "centimeters";
lgd_position = [...
    ax_left.Position(1) + (ax_center.Position(1) + ax_center.Position(3) - ax_left.Position(1) - 8.2) / 2, ...
    ax_left.Position(2) - 3.5, ...
    8.2, ...
    1.8];
lgd = legend(ax, ghost_plots, ...
    NumColumns=3, ...
    Box="off", ...
    IconColumnWidth=20, ...
    Units="centimeters", ...
    Position=lgd_position);

% Subplot letters
writePanelLetter(nexttile(1, [1, 1]), "a", -0.9, -0.1);
writePanelLetter(nexttile(2, [1, 1]), "b", -0.9, -0.1);
writePanelLetter(nexttile(3, [1, 1]), "c", -0.9, -0.1);
writePanelLetter(nexttile(6, [1, 1]), "d", -0.9, -0.1);

% Set font globally
fontname(f, "arial");


%% === Save figure ========================================================

exportgraphics(f, fullfile(getPath("Figures"), "figS7.pdf"), ContentType="vector");
exportgraphics(f, fullfile(getPath("Figures"), "figS7.png"), Resolution=600);
