% Fig. S1 | Specificity of information content in RNN cohorts.
% 
%   - a, Decoding accuracy of each type of option values (lines) is shown
% for each RNN cohort (columns).
% 
%   - b, Neural distance trajectories between OFC and RNN cohorts during
% rational training. Points show the average distance between activity
% patterns of OFC recordings and RNN models (across the 1,000 RNN
% instances), computed using either RDMs (x-axis) or CCMs (y-axis) metrics,
% either at initialization (black dots) or at training convergence (see
% legend). This is a simple summary of Fig. 2c in the main text.


%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

Data = loadMeasureResults([...
        "config_ID", "is_rational", "fit_step", ...
        "R2_decode_both_attention", "R2_decode_diff_attention", ...
        "R2_decode_both_order", "R2_decode_diff_order", ...
        "R2_decode_both_loc", "R2_decode_diff_loc", ...
        "dist_RDM_avg_OFC", "dist_CCM_avg_OFC"], ...
        "rational_last");


%% === Generate figure ====================================================

% Initialize the figure
f = figure(...
    Name = "Figure S1: specificity of information content in RNN cohorts", ...
    Units = "centimeters", ...
    Position = [0, 0, 18, 7], ...
    NumberTitle="off", ...
    Color = "w");
movegui(f, "center");

% Define the layout
t = tiledlayout(f, 1, 3, ...
    TileSpacing="loose", ...
    Units="centimeters", ...
    Position=[2.8, 3, 14.8, 3.7]);

% Subplots
plotInformationDecodingAccuracy(nexttile(1, [1, 2]), Data);
plotSimpleNeuralDistanceTrajectory(nexttile(3, [1, 1]), Data);

% Subplot letters
writePanelLetter(nexttile(1, [1, 2]), "a", -0.4, 1);
writePanelLetter(nexttile(3, [1, 1]), "b", -0.4, 1);

% Legend
ghost_plots = gobjects(1, 15);
ax = nexttile(3, [1, 1]);
hold(ax, "on");
ghost_plots(1) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfnetwork value");
ghost_plots(2) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfcomputation");
ghost_plots(3) = plot(ax, NaN, NaN, Marker="s", MarkerFaceColor=defineModelColor(1), MarkerEdgeColor="none", LineStyle="none", ...
    DisplayName="comparison");
ghost_plots(4) = plot(ax, NaN, NaN, Marker="s", MarkerFaceColor=defineModelColor(2), MarkerEdgeColor="none", LineStyle="none", ...
    DisplayName="synthesis");
ghost_plots(5) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="");
ghost_plots(6) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfattended option");
ghost_plots(7) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfidentity format");
ghost_plots(8) = plot(ax, NaN, NaN, Color="k", LineStyle=defineModelLineStyle(1), LineWidth=0.7, ...
    DisplayName=" spatial");
ghost_plots(9) = plot(ax, NaN, NaN, Color="k", LineStyle=defineModelLineStyle(7), LineWidth=0.7, ...
    DisplayName=" temporal");
ghost_plots(10) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="");
ghost_plots(11) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfvalue readout");
ghost_plots(12) = plot(ax, NaN, NaN, LineStyle="none", ...
    DisplayName="\bfformat");
ghost_plots(13) = plot(ax, NaN, NaN, Marker=defineModelMarker(1), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="spatial");
ghost_plots(14) = plot(ax, NaN, NaN, Marker=defineModelMarker(3), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="temporal");
ghost_plots(15) = plot(ax, NaN, NaN, Marker=defineModelMarker(5), MarkerFaceColor="none", MarkerEdgeColor="k", LineStyle="none", LineWidth=0.7, ...
    DisplayName="attentional");
hold(ax, "off");
lgd = legend(ax, ghost_plots, ...
    NumColumns=3, ...
    Box="off", ...
    IconColumnWidth=20);
lgd.Layout.Tile = "south";

% Set font globally
fontname(f, "arial");


%% === Save figure ========================================================

exportgraphics(f, fullfile(getPath("Figures"), "figS1.pdf"), ContentType="vector");
exportgraphics(f, fullfile(getPath("Figures"), "figS1.png"), Resolution=600);
