% Description here

% Initialize the figure
f = figure(...
    Name = "Figure 3: behavioral and neural realism of candudare RNN models of the OFC", ...
    Units = "centimeters", ...
    Position = [0, 0, 16, 12], ...
    Color = "w");
movegui(f, "center");

% Load the data
Data = loadMeasureResults([...
    "config_ID", "fit_label", "is_rational", "is_irrational", ...
    "dist_CCM_avg_OFC", "dist_CCM_same_OFC", "dist_CCM_other_OFC", ...
    "bacc_Franck", "bacc_Miles", "bacc_same_monkey", "bacc_other_monkey", ...
    "dist_CCM_avg_ACC", "dist_CCM_avg_dlPFC"], ...
    "rational_last");

% Define the layout
t = tiledlayout(f, 1, 3);

% Subplots
plotCCMdistanceDistribPerArea(nexttile(1), Data);
plotCCMdistanceDistribPerFit(nexttile(2), Data);
plotMonkeyBaccDistribPerFit(nexttile(3), Data);