% Statistical analysis for Figure 4b, 4c, 4j, 4k and section
% "Characterizing irrational interferences in value computations".
%
% This script performs all required statistical comparisons. It operates on
% precomputed measures and evaluates predefined contrasts across model
% configurations and experimental factors.
%
% OUTPUTS -----------------------------------------------------------------
% A structured statistics table saved to:
%   results/metrics/interferences.mat
%   results/metrics/interferences.csv
%
% Each row of the table corresponds to a single statistical test and
% includes test metadata, summary statistics, and inferential results.

%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

Data = loadMeasureResults([...
    "config_ID", "is_rational", "is_irrational", ...
    "std_order_per_step", ...
    "std_order_attribute_per_step", "std_order_option_per_step", ...
    "value_function_attended_gradient_diff"], ...
    "rational_last");


%% === Test and store results =============================================

stats_table = initializeStatsTable();

for config_ID = 1:10

    select_config = (Data.config_ID == config_ID);

    % --- Compare order interferences between rational and irrational models --- %

    for decision_step = 2:4
        group1 = Data.std_order_per_step(decision_step - 1, select_config & Data.is_rational)';
        group1 = repmat(group1, 2, 1);
        group2 = Data.std_order_per_step(decision_step - 1, select_config & Data.is_irrational)';
        stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
            0.05 / 10, ...
            dependent_variable="std_order_step_" + num2str(decision_step), ...
            independent_variable="fit_phase", ...
            independent_variable_levels=["rational", "irrational"], ...
            subset_factors="model_config", ...
            subset_levels=config_ID);
    end

    % --- Compare interferences at different decision steps --- %

    group1 = Data.std_order_per_step(1, select_config & Data.is_irrational)';
    group2 = Data.std_order_per_step(2, select_config & Data.is_irrational)';
    group3 = Data.std_order_per_step(3, select_config & Data.is_irrational)';

    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="std_order", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 3], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);

    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group3, ...
        0.05 / 10, ...
        dependent_variable="std_order", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 4], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);

    stats_table = addPairedTtestStatsTableRow(stats_table, group2, group3, ...
        0.05 / 10, ...
        dependent_variable="std_order", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[3, 4], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);

    % --- Compare interferences between option and attribute trials --- %

    for decision_step = 2:4
        group1 = Data.std_order_option_per_step(decision_step - 1, select_config & Data.is_irrational)';
        group2 = Data.std_order_attribute_per_step(decision_step - 1, select_config & Data.is_irrational)';
        stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
            0.05 / 10, ...
            dependent_variable="std_order_step_" + num2str(decision_step), ...
            independent_variable="trial_type", ...
            independent_variable_levels=["option", "attribute"], ...
            subset_factors=["model_config", "fit_phase"], ...
            subset_levels=[config_ID, "irrational"]);
    end

    % --- Attentional gradient difference between rational and irrational models --- %

    group1 = Data.value_function_attended_gradient_diff(select_config & Data.is_rational)';
    group1 = repmat(group1, 2, 1);
    group2 = Data.value_function_attended_gradient_diff(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group2, group3, ...
        0.05 / 10, ...
        dependent_variable="value_function_attended_gradient_diff", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

end


%% === Save ===============================================================

% Save as .mat file
save(fullfile(getPath("Metrics"), "interferences.mat"), "stats_table");

% Export to .csv (except raw data)
stats_table.raw_data = [];
writetable(stats_table, fullfile(getPath("Metrics"), "interferences.csv"));
