% Statistical analysis for Figure 3e and section "Identifying value
% computations in the OFC". 
%
% This script performs all required statistical comparisons. It operates on
% precomputed measures and evaluates predefined contrasts across model
% configurations and experimental factors.
%
% OUTPUTS -----------------------------------------------------------------
% A structured statistics table saved to:
%   results/metrics/model_behaviour.mat
%   results/metrics/model_behaviour.csv
%
% Each row of the table corresponds to a single statistical test and
% includes test metadata, summary statistics, and inferential results.

%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

Data = loadMeasureResults([...
    "config_ID", "is_rational", "is_irrational", "fit_label", ...
    "bacc_Franck", "bacc_Miles", "bacc_other_monkey", "bacc_same_monkey"], ...
    "rational_last");


%% === Test and store results =============================================

stats_table = initializeStatsTable();

% --- Compare monkey choice predictivity between rational and irrational
% models for all conhorts --- %

group1 = Data.bacc_Franck(Data.is_rational)';
group1 = repmat(group1, 2, 1);
group2 = Data.bacc_Franck(Data.is_irrational)';
stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
    0.05 / 10, ...
    dependent_variable="bacc_Franck", ...
    independent_variable="fit_phase", ...
    independent_variable_levels=["rational", "irrational"], ...
    subset_factors="", ...
    subset_levels="");

group1 = Data.bacc_Miles(Data.is_rational)';
group1 = repmat(group1, 2, 1);
group2 = Data.bacc_Miles(Data.is_irrational)';
stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
    0.05 / 10, ...
    dependent_variable="bacc_Miles", ...
    independent_variable="fit_phase", ...
    independent_variable_levels=["rational", "irrational"], ...
    subset_factors="", ...
    subset_levels="");


for config_ID = 1:10

    select_config = (Data.config_ID == config_ID);

    % --- Compare monkey choice predictivity between rational and irrational models --- %

    % Predictivity of each monkey's choices

    group1 = Data.bacc_Franck(select_config & Data.is_rational)';
    group1 = repmat(group1, 2, 1);
    group2 = Data.bacc_Franck(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_Franck", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    group1 = Data.bacc_Miles(select_config & Data.is_rational)';
    group1 = repmat(group1, 2, 1);
    group2 = Data.bacc_Miles(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_Miles", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    % Predictivity of choices of the same monkey used for re-training

    group1 = Data.bacc_Franck(select_config & Data.is_rational)';
    group2 = Data.bacc_same_monkey(select_config & Data.is_irrational & ...
        contains(Data.fit_label, "Franck"))';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_same_Franck", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    group1 = Data.bacc_Miles(select_config & Data.is_rational)';
    group2 = Data.bacc_same_monkey(select_config & Data.is_irrational & ...
        contains(Data.fit_label, "Miles"))';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_same_Miles", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    % Predictivity of choices of the other monkey than the one used for
    % re-training

    group1 = Data.bacc_Franck(select_config & Data.is_rational)';
    group2 = Data.bacc_other_monkey(select_config & Data.is_irrational & ...
        contains(Data.fit_label, "Franck"))';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_other_Franck", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    group1 = Data.bacc_Miles(select_config & Data.is_rational)';
    group2 = Data.bacc_other_monkey(select_config & Data.is_irrational & ...
        contains(Data.fit_label, "Miles"))';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="bacc_other_Miles", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

end


%% === Save ===============================================================

% Save as .mat file
save(fullfile(getPath("Metrics"), "model_behaviour.mat"), "stats_table");

% Export to .csv (except raw data)
stats_table.raw_data = [];
writetable(stats_table, fullfile(getPath("Metrics"), "model_behaviour.csv"));
