% Statistical analysis for Figure 3d, 4d and 4e.
%
% This script performs all required statistical comparisons. It operates on
% precomputed measures and evaluates predefined contrasts across model
% configurations and experimental factors.
%
% OUTPUTS -----------------------------------------------------------------
% A structured statistics table saved to:
%   results/metrics/monkey_behaviour.mat
%   results/metrics/monkey_behaviour.csv
%
% Each row of the table corresponds to a single statistical test and
% includes test metadata, summary statistics, and inferential results.

%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

ModelData = loadMeasureResults(["is_rational", "value_function"], "rational_last");

ValueProfile = load(fullfile(getPath("MonkeyData"), "ValueProfile.mat"));
PropIrrational = load(fullfile(getPath("MonkeyData"), "PropIrrational.mat"));
DecisionResiduals = load(fullfile(getPath("MonkeyData"), "DecisionResiduals.mat"));
CueAttentionPollution = load(fullfile(getPath("MonkeyData"), "CueAttentionPollution.mat"));


%% === Test and store results =============================================

stats_table = initializeStatsTable();

% --- Assess difference in correlation between monkey value profiles and
% rational value profile --- %

group1 = zscore(mean(ModelData.value_function(:, ModelData.is_rational), 2));
group2 = zscore(reshape(ValueProfile.Franck.value_function, [], 1));
group3 = zscore(reshape(ValueProfile.Miles.value_function, [], 1));
[r12, ~] = corr(group1, group2, type="Pearson");
[r13, ~] = corr(group1, group3, type="Pearson");
[r23, ~] = corr(group2, group3, type="Pearson");
n = length(group1);

% Williams test
K = 1 - (r12^2) - (r13^2) - (r23^2) + 2 * r12 * r13 * r23;
t = (r12 - r13) * sqrt((n - 1) * (1 + r23)) / ...
    sqrt((2 * K * (n - 1) / (n - 3)) + ((r12 + r13) ^ 2) * ((1 - r23) ^ 3) / 4);
p = 2 * (1 - tcdf(abs(t), n-3));

% Add line
stats_table = addStatsTableRow(stats_table, r12, r13, ...
    test_name="williams_test", ...
    dependent_variable="value_profile_corr_with_rational", ...
    independent_variable="monkey", ...
    independent_variable_levels=["Franck", "Miles"], ...
    degrees_freedom=n, ...
    p_value=p, ...
    p_value_threshold=0.05);


for monkey = ["Franck", "Miles"]

    % --- Compare monkey value profiles to rational value profile --- %

    group1 = zscore(mean(ModelData.value_function(:, ModelData.is_rational), 2));
    group2 = zscore(reshape(ValueProfile.(monkey).value_function, [], 1));
    stats_table = addPearsonCorrelationTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 2, ...
        dependent_variable="value_profile", ...
        independent_variable="system", ...
        independent_variable_levels=["rational_RNNs", monkey], ...
        subset_factors="", ...
        subset_levels="");

    % --- Compare monkey irrational choices at different choice steps --- %

    group1 = PropIrrational.(monkey).both{2};
    group2 = PropIrrational.(monkey).both{3};
    group3 = PropIrrational.(monkey).both{4};

    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 2, ...
        dependent_variable="prop_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 3], ...
        subset_factors="monkey", ...
        subset_levels=monkey);
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group3, ...
        0.05 / 2, ...
        dependent_variable="prop_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 4], ...
        subset_factors="monkey", ...
        subset_levels=monkey);
    stats_table = addPairedTtestStatsTableRow(stats_table, group2, group3, ...
        0.05 / 2, ...
        dependent_variable="prop_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[3, 4], ...
        subset_factors="monkey", ...
        subset_levels=monkey);

    % --- Compare monkey P(irrational) corrected at difference choice steps --- %

    group1 = DecisionResiduals.(monkey).both{2};
    group2 = DecisionResiduals.(monkey).both{3};
    group3 = DecisionResiduals.(monkey).both{4};

    stats_table = addTwoSampleTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 2, ...
        dependent_variable="residuals_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 3], ...
        subset_factors="monkey", ...
        subset_levels=monkey);
    stats_table = addTwoSampleTtestStatsTableRow(stats_table, group1, group3, ...
        0.05 / 2, ...
        dependent_variable="residuals_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[2, 4], ...
        subset_factors="monkey", ...
        subset_levels=monkey);
    stats_table = addTwoSampleTtestStatsTableRow(stats_table, group2, group3, ...
        0.05 / 2, ...
        dependent_variable="residuals_irrational", ...
        independent_variable="decision_step", ...
        independent_variable_levels=[3, 4], ...
        subset_factors="monkey", ...
        subset_levels=monkey);

    % --- Compare monkey P(irrational) corrected between option and attribute trials --- %

    for decision_step = 2:4

        group1 = DecisionResiduals.(monkey).option{decision_step};
        group2 = DecisionResiduals.(monkey).attribute{decision_step};
        stats_table = addTwoSampleTtestStatsTableRow(stats_table, group1, group2, ...
            0.05 / 2, ...
            dependent_variable="residuals_irrational_step_" + num2str(decision_step), ...
            independent_variable="trial_type", ...
            independent_variable_levels=["option", "attribute"], ...
            subset_factors="monkey", ...
            subset_levels=monkey);
    end

end


%% === Save ===============================================================

% Save as .mat file
save(fullfile(getPath("Metrics"), "monkey_behaviour.mat"), "stats_table");

% Export to .csv (except raw data)
stats_table.raw_data = [];
writetable(stats_table, fullfile(getPath("Metrics"), "monkey_behaviour.csv"));
