% Statistical analysis for Figure 3f, 3g, S7d, and section "Identifying
% value computations in the OFC". 
%
% This script performs all required statistical comparisons. It operates on
% precomputed measures and evaluates predefined contrasts across model
% configurations and experimental factors.
%
% OUTPUTS -----------------------------------------------------------------
% A structured statistics table saved to:
%   results/metrics/neural_distance.mat
%   results/metrics/neural_distance.csv
%
% Each row of the table corresponds to a single statistical test and
% includes test metadata, summary statistics, and inferential results.

%% === Environment set-up =================================================

setup;
clear variables;
close all;


%% === Load data ==========================================================

% Generate all neural distance measure labels
distance_monkey_target = ["Franck", "Miles", "avg", "both", "other", "same"];
distance_area_target = ["OFC", "dlPFC", "ACC"];
distance_metric = ["RDM", "CCM"];
n_distance_measures = length(distance_monkey_target) ...
    * length(distance_area_target) ...
    * length(distance_metric);
neural_distance_labels = strings(1, n_distance_measures);

i_label = 1;
for monkey = distance_monkey_target
    for area = distance_area_target
        for metric = distance_metric
            neural_distance_labels(i_label) = sprintf("dist_%s_%s_%s", metric, monkey, area);
            i_label = i_label + 1;
        end
    end
end

% Load them
Data = loadMeasureResults([...
    "config_ID", "is_rational", "is_irrational", "fit_step", ...
    neural_distance_labels], ...
    "rational_last");


%% === Test and store results =============================================

stats_table = initializeStatsTable();

for config_ID = 1:10

    select_config = (Data.config_ID == config_ID);

    % --- Compare neural distance between initial and rational state --- %

    group1 = Data.dist_RDM_avg_OFC(select_config & Data.fit_step == 1)';
    group2 = Data.dist_RDM_avg_OFC(select_config & Data.is_rational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_RDM_avg_OFC", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["initial", "rational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    group1 = Data.dist_CCM_avg_OFC(select_config & Data.fit_step == 1)';
    group2 = Data.dist_CCM_avg_OFC(select_config & Data.is_rational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_avg_OFC", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["initial", "rational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    % --- Compare neural distance between rational and irrational state --- %

    group1 = Data.dist_CCM_avg_OFC(select_config & Data.is_rational)';
    group1 = repmat(group1, 2, 1);
    group2 = Data.dist_CCM_avg_OFC(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_avg_OFC", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);
    
    group2 = Data.dist_CCM_same_OFC(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_same_OFC", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);
    
    group2 = Data.dist_CCM_other_OFC(select_config & Data.is_irrational)';
    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_other_OFC", ...
        independent_variable="fit_phase", ...
        independent_variable_levels=["rational", "irrational"], ...
        subset_factors="model_config", ...
        subset_levels=config_ID);

    % --- Compare neural distance between the OFC, dlPFC and ACC --- %

    group1 = Data.dist_CCM_avg_OFC(select_config & Data.is_irrational)';
    group2 = Data.dist_CCM_avg_dlPFC(select_config & Data.is_irrational)';
    group3 = Data.dist_CCM_avg_ACC(select_config & Data.is_irrational)';

    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group2, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_avg", ...
        independent_variable="area", ...
        independent_variable_levels=["OFC", "dlPFC"], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);

    stats_table = addPairedTtestStatsTableRow(stats_table, group1, group3, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_avg", ...
        independent_variable="area", ...
        independent_variable_levels=["OFC", "ACC"], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);
    
    stats_table = addPairedTtestStatsTableRow(stats_table, group2, group3, ...
        0.05 / 10, ...
        dependent_variable="dist_CCM_avg", ...
        independent_variable="area", ...
        independent_variable_levels=["dlPFC", "ACC"], ...
        subset_factors=["model_config", "fit_phase"], ...
        subset_levels=[config_ID, "irrational"]);

end


%% === Save ===============================================================

% Save as .mat file
save(fullfile(getPath("Metrics"), "neural_distance.mat"), "stats_table");

% Export to .csv (except raw data)
stats_table.raw_data = [];
writetable(stats_table, fullfile(getPath("Metrics"), "neural_distance.csv"));
