function [] = plotCCM(ax, CCM_option, CCM_attribute, ...
    CCM_option_p, CCM_attribute_p, plot_options)
% Code for figure 2b and M1C.
%
% INPUTS ------------------------------------------------------------------
% ax : <matlab.graphics.axis.Axes 1x1>
%     Axes handle where the plot should be drawn.
%
% CCM_option : <double 9x9>
%     Cross-correlation matrix computed on option trials. See also:
%     computeCCM.
%
% CCM_attribute : <double 9x9>
%     Cross-correlation matrix computed on attribute trials. See also:
%     computeCCM.
%
% CCM_option_p, CCM_attribute_p : <double 9x9>
%     P-values associated with each entry of the CCMs. See also:
%     computeCCM.
%
% rng, marker_size :
%     Name-value parameters controlling visual properties of the plot.
%
% OUTPUTS -----------------------------------------------------------------
% None. The function draws into the provided axes.

arguments
    ax (1, 1) matlab.graphics.axis.Axes
    CCM_option (9, 9) double
    CCM_attribute (9, 9) double
    CCM_option_p (9, 9) double
    CCM_attribute_p (9, 9) double
    plot_options.color_thin (1, 3) double = 0.6 * ones(1, 3)
    plot_options.line_width_thin (1, 1) double = 0.2
    plot_options.color_thick (1, 3) double = 0 * ones(1, 3)
    plot_options.line_width_thick (1, 1) double = 0.8
    plot_options.p_threshold (1, 1) double = 0.05 / (36 * 2)
    plot_options.font_size_text_label (1, 1) double = 5.5
    plot_options.font_size_trial_type (1, 1) double = 8
    plot_options.star_font_size (1, 1) double = 16
    plot_options.star_y_shift (1, 1) double = 0.3
    plot_options.y_label (1,1 ) string = ""
    plot_options.title (1,1 ) string = ""
    plot_options.labels (1, 4) logical = [false, false, false, false]
end

hold(ax, "on");

% Merge CCMs in the same matrix
CCM = NaN(10);
select_half_10 = triu(true(10), 2);
select_half_9 = triu(true(9), 1);
CCM(select_half_10) = CCM_attribute(select_half_9);
CCM(select_half_10') = CCM_option(select_half_9');
show_cell = true(size(CCM));
show_cell(diag(true(10, 1))) = false;
show_cell(diag(true(9, 1), 1)) = false;
show_cell(diag(true(9, 1), -1)) = false;

% --- Plot --- %

% Heatmap
imagesc(ax, flipud(CCM), AlphaData=flipud(show_cell));

% Thin grid
for gap = [1, 2, 4, 5, 7, 8]
    plot(ax, [0.5 + gap, 0.5 + gap], [0.5, 9.5 - gap], ...
        Color=plot_options.color_thin, ...
        LineWidth=plot_options.line_width_thin);
    plot(ax, [0.5, 9.5 - gap], [0.5 + gap, 0.5 + gap], ...
        Color=plot_options.color_thin, ...
        LineWidth=plot_options.line_width_thin);
    plot(ax, [10.5 - gap, 10.5 - gap], [1.5 + gap, 10.5], ...
        Color=plot_options.color_thin, ...
        LineWidth=plot_options.line_width_thin);
    plot(ax, [1.5 + gap, 10.5], [10.5 - gap, 10.5 - gap], ...
        Color=plot_options.color_thin, ...
        LineWidth=plot_options.line_width_thin);
end

% Thick grid
for gap = 0:3:9
    plot(ax, [0.5 + gap, 0.5 + gap], [0.5, 9.5 - gap], ...
        Color=plot_options.color_thick, ...
        LineWidth=plot_options.line_width_thick);
    plot(ax, [0.5, 9.5 - gap], [0.5 + gap, 0.5 + gap], ...
        Color=plot_options.color_thick, ...
        LineWidth=plot_options.line_width_thick);
    plot(ax, [10.5 - gap, 10.5 - gap], [1.5 + gap, 10.5], ...
        Color=plot_options.color_thick, ...
        LineWidth=plot_options.line_width_thick);
    plot(ax, [1.5 + gap, 10.5], [10.5 - gap, 10.5 - gap], ...
        Color=plot_options.color_thick, ...
        LineWidth=plot_options.line_width_thick);
end

% Diagonals
plot(ax, [9.5, 0.5], [0.5, 9.5], ...
    Color=plot_options.color_thick, ...
    LineWidth=plot_options.line_width_thick);
plot(ax, [10.5, 1.5], [1.5, 10.5], ...
    Color=plot_options.color_thick, ...
    LineWidth=plot_options.line_width_thick);

% --- Text labels --- %

% Time
shift_t = 0.05;
for t = 1:3
    for cue = 0:2
        text_color =(0.2 * (4 - t) - 0.1) * ones(1, 3);
        if plot_options.labels(1)
            text(ax, t + cue * 3, - shift_t, ...
                "t" + string(t), ...
                FontName="Arial", ...
                FontSize=plot_options.font_size_text_label, ...
                HorizontalAlignment="center", ...
                Color=text_color);
        end
        if plot_options.labels(2)
            text(ax, - shift_t, 4  - t + cue * 3, ...
                "t" + string(t), ...
                FontName="Arial", ...
                FontSize=plot_options.font_size_text_label, ...
                HorizontalAlignment="center", ...
                Color=text_color);
        end
        if plot_options.labels(3)
            text(ax, 1 + t + cue * 3, 11 + shift_t, ...
                "t" + string(t), ...
                FontName="Arial", ...
                FontSize=plot_options.font_size_text_label, ...
                HorizontalAlignment="center", ...
                Color=text_color);
        end
        if plot_options.labels(4)
            text(ax, 11 + shift_t, 5 - t + cue * 3, ...
                "t" + string(t), ...
                FontName="Arial", ...
                FontSize=plot_options.font_size_text_label, ...
                HorizontalAlignment="center", ...
                Color=text_color);
        end
    end
end

% Cue rank
shift_cue = 0.8;
for i_cue = 1:3
    text_color = (0.2 * (4 - i_cue) - 0.1) * ones(1, 3);
    if plot_options.labels(1)
        text(ax, 2 + (i_cue - 1) * 3, - shift_cue, ...
            "Cue " + string(i_cue), ...
            FontName="Arial", ...
            FontSize=plot_options.font_size_text_label, ...
            HorizontalAlignment="center", ...
            Color=text_color);
    end
    if plot_options.labels(3)
        text(ax, 3 + (i_cue - 1) * 3, 11 + shift_cue, ...
            "Cue " + string(i_cue), ...
            FontName="Arial", ...
            FontSize=plot_options.font_size_text_label, ...
            HorizontalAlignment="center", ...
            Color=text_color);
    end
    if plot_options.labels(2)
        text(ax, - shift_cue, 2 + (3 - i_cue) * 3, ...
            "Cue " + string(i_cue), ...
            Rotation=90, ...
            FontName="Arial", ...
            FontSize=plot_options.font_size_text_label, ...
            HorizontalAlignment="center", ...
            Color=text_color);
    end
    if plot_options.labels(4)
        text(ax, 11 + shift_cue, 3 + (3 - i_cue) * 3, ...
            "Cue " + string(i_cue), ...
            Rotation=90, ...
            FontName="Arial", ...
            FontSize=plot_options.font_size_text_label, ...
            HorizontalAlignment="center", ...
            Color=text_color);
    end
end

% Trial type
text(ax, 3.3, 7.25, "Option trials", ...
    FontSize=plot_options.font_size_trial_type, ...
    FontName="Arial", ...
    HorizontalAlignment="center", ...
    Rotation=45);
text(ax, 7.3, 4.1, "Attribute trials", ...
    FontSize=plot_options.font_size_trial_type, ...
    FontName="Arial", ...
    HorizontalAlignment="center", ...
    Rotation=45);

% --- Aesthetics --- %

axis(ax, "square");
set(ax, ...
    XAxisLocation="top", ...
    Ydir="reverse", ...
    CLim=[-1, 1], ...
    XColor="none", ...
    YColor="none");
xlim(ax, [0.5, 10.5]);
ylim(ax, [0.5, 10.5]);
setAxFontSize(ax);
colormap(ax, defineDivergentColormap());
if ~ isempty(plot_options.y_label)
    text(ax, -1.7, 5.5, plot_options.y_label, ...
        FontSize=8, ...
        FontWeight="bold", ...
        Rotation=90, ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle");
end
if ~ isempty(plot_options.title)
    text(ax, 5.5, -1.7, plot_options.title, ...
        FontSize=8, ...
        FontWeight="bold", ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle");
end

% --- Highlight significative cells --- %

half_matrix = triu(ones(9), 1);
is_signif_option = CCM_option_p <= plot_options.p_threshold;
is_signif_option = is_signif_option .* half_matrix';
is_signif_attribute = CCM_attribute_p <= plot_options.p_threshold;
is_signif_attribute = is_signif_attribute .* half_matrix;
[row_option, col_option] = find(is_signif_option);
[row_attribute, col_attribute] = find(is_signif_attribute);
for i_option_cell = 1:length(row_option)
    x = col_option(i_option_cell);
    y = 10 - row_option(i_option_cell) + plot_options.star_y_shift;
    text(ax, x, y, "*", ...
        FontSize=plot_options.star_font_size, ...
        Color="w", ...
        FontWeight="bold", ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle");
end
for i_attribute_cell = 1:length(row_attribute)
    x = col_attribute(i_attribute_cell) + 1;
    y = 11 - row_attribute(i_attribute_cell) + plot_options.star_y_shift;
    text(ax, x, y, "*", ...
        FontSize=plot_options.star_font_size, ...
        Color="w", ...
        FontWeight="bold", ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle");
end

hold(ax, "off");
