function [] = plotMonkeyChoiceDifficulty(ax, ChoiceDifficulty, plot_options)
% Code for figure 4d and 4e.
%
% INPUTS ------------------------------------------------------------------
% ax : <matlab.graphics.axis.Axes 1x1>
%     Axes handle where the plot should be drawn.
%
% ChoiceDifficulty : <struct 1x1>
%     Structure containing the absolute subjective value difference across
%     trials, at the decision step. See also:
%     computeMonkeyChoiceDifficulty.
%
% line_width, monkey_line_style, marker_size :
%     Name-value parameters controlling visual properties of the plot.
%
% OUTPUTS -----------------------------------------------------------------
% None. The function draws into the provided axes.

arguments
    ax (1, 1) matlab.graphics.axis.Axes
    ChoiceDifficulty (1, 1) struct
    plot_options.x_shift (1, 1) double = 0.05
    plot_options.cap_size (1, 1) double = 0
    plot_options.line_width (1, 1) double = 0.5
    plot_options.marker_size (1, 1) double = 6
    plot_options.marker_edge_color (1, 3) double = [1, 1, 1]
    plot_options.line_style_option (1, 1) string = "-"
    plot_options.line_style_attribute (1, 1) string = "--"

end

hold(ax, "on");

% Aesthetics
xlim(ax, [1.5, 4.5]);
ylim(ax, [0, 2.5]);
xticks(ax, 2:4);
xlabel(ax, "Within-trial time step");
ylabel(ax, "|\DeltaV|");
setAxFontSize(ax);

% ~ Loop over monkey and trial type ~ %
for monkey = ["Franck", "Miles"]

    for trial_type = ["option", "attribute"]

        % Define x coordinates
        x_coord = 2:4;
        if monkey == "Franck"
            x_coord = x_coord - plot_options.x_shift;
        else
            x_coord = x_coord + plot_options.x_shift;
        end
        if trial_type == "option"
            x_coord = x_coord - (plot_options.x_shift / 2);
        else
            x_coord = x_coord + (plot_options.x_shift / 2);
        end

        % Plot with error bars
        errorbar(ax, ...
            x_coord, ...
            ChoiceDifficulty.(monkey).(trial_type + "_mean")(2:4), ...
            ChoiceDifficulty.(monkey).(trial_type + "_se")(2:4), ...
            CapSize=plot_options.cap_size, ...
            Marker=defineMonkeyMarker(monkey), ...
            MarkerSize=plot_options.marker_size, ...
            MarkerFaceColor=defineMonkeyColor(monkey), ...
            Color=defineMonkeyColor(monkey), ...
            MarkerEdgeColor=plot_options.marker_edge_color, ...
            LineWidth=plot_options.line_width, ...
            LineStyle=plot_options.("line_style_" + trial_type));

    end
end

% Legend
ghost_plots = gobjects(1, 4);
ghost_plots(1) = plot(ax, NaN, NaN, ...
    Marker=defineMonkeyMarker("Franck"),...
    MarkerSize=plot_options.marker_size, ...
    MarkerFaceColor=defineMonkeyColor("Franck"), ...
    Color=defineMonkeyColor("Franck"), ...
    MarkerEdgeColor=plot_options.marker_edge_color, ...
    LineWidth=plot_options.line_width, ...
    DisplayName="Monkey F");
ghost_plots(2) = plot(ax, NaN, NaN, ...
    Marker=defineMonkeyMarker("Miles"),...
    MarkerSize=plot_options.marker_size, ...
    MarkerFaceColor=defineMonkeyColor("Miles"), ...
    Color=defineMonkeyColor("Miles"), ...
    MarkerEdgeColor=plot_options.marker_edge_color, ...
    LineWidth=plot_options.line_width, ...
    DisplayName="Monkey M");
ghost_plots(3) = plot(ax, NaN, NaN, ...
    Color="k", ...
    LineWidth=plot_options.line_width, ...
    LineStyle=plot_options.line_style_option, ...
    DisplayName="Option trials");
ghost_plots(4) = plot(ax, NaN, NaN, ...
    Color="k", ...
    LineWidth=plot_options.line_width, ...
    LineStyle=plot_options.line_style_attribute, ...
    DisplayName="Attribute trials");
legend(ax, ghost_plots, ...
    NumColumns=2, ...
    Box="off", ...
    Location="northoutside", ...
    IconColumnWidth=15);

hold(ax, "off");
